# Generated by Django 4.0.3 on 2022-03-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alogin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alogin',
            name='name',
        ),
    ]
